---
# roles/common/tasks/main.yml

- name: Write sources.list
  template: src={{item.src}} dest={{item.dest}} owner={{item.owner}} group={{item.group}} mode={{item.mode}}
  with_items: ${sources_list}
  tags: sources-list

- name: Install editor
  apt: pkg={{item}} force=yes update_cache=yes
  with_items: ${editor}
  tags: editor

- name: Install basic pkgs
  apt: pkg={{item}}
  with_items: ${basic_pkgs}
  tags: basic-pkgs

- name: Install basic devel pkgs
  apt: pkg={{item}}
  with_items: ${devel_pkgs}
  tags: devel-pkgs

- name: Pip install basic python pkgs
  pip: name={{item}}
  with_items: ${python_pkgs}
  tags: python-pkgs

- name: Git clone my repos
  sudo: False
  git: repo={{item.repo}} dest={{item.dest}}
  with_items: ${my_repos}
  tags: my-repos

- name: Write config files
  sudo: False
  template: src={{item.src}} dest={{item.dest}} owner={{item.owner}} group={{item.group}} mode={{item.mode}}
  with_items: ${config_files}
  tags: config-files

- name: Change default shell
  user: name={{item.user}} shell={{item.shell}}
  with_items: ${default_shell}
  tags: default-shell
